version: '3'
services:
  web:
    restart: "no"
    build: . # build an image using the ./Dockerfile
    ports:
      - "5000:5000"
    expose:
      - "5000"
    command: ["gunicorn", "--workers", "3", "--bind", "0.0.0.0:5000", "wsgi:app"]
    #command: ["flask", "run", "--host=0.0.0.0"]
